version: '3.3'

services:
  pv_centralized:
    env_file: ../conf.env
    build:
      context: '.'
      dockerfile: './Dockerfile'
    networks: 
      - edgeflex-network
    volumes:
      - .:/centralized
    command: bash -c "cd centralized && 
                      make init &&
                      cd .. &&
                      /centralized/covee/bin/python3 /centralized/Control_main.py --ext_port 7071"
    # command:          tail -F dfsdfödslk
    ports:
      - 7071:8000

networks:
  edgeflex-network:
    external:
      name: edgeflex-network